/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.djames.kafka.streams.example.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Page extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8690440481300891584L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Page\",\"namespace\":\"org.djames.kafka.streams.example.model\",\"fields\":[{\"name\":\"pageID\",\"type\":\"int\"},{\"name\":\"category\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Page> ENCODER =
      new BinaryMessageEncoder<Page>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Page> DECODER =
      new BinaryMessageDecoder<Page>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Page> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Page> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Page> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Page>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Page to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Page from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Page instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Page fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int pageID;
   private java.lang.CharSequence category;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Page() {}

  /**
   * All-args constructor.
   * @param pageID The new value for pageID
   * @param category The new value for category
   */
  public Page(java.lang.Integer pageID, java.lang.CharSequence category) {
    this.pageID = pageID;
    this.category = category;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pageID;
    case 1: return category;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pageID = (java.lang.Integer)value$; break;
    case 1: category = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'pageID' field.
   * @return The value of the 'pageID' field.
   */
  public int getPageID() {
    return pageID;
  }


  /**
   * Sets the value of the 'pageID' field.
   * @param value the value to set.
   */
  public void setPageID(int value) {
    this.pageID = value;
  }

  /**
   * Gets the value of the 'category' field.
   * @return The value of the 'category' field.
   */
  public java.lang.CharSequence getCategory() {
    return category;
  }


  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(java.lang.CharSequence value) {
    this.category = value;
  }

  /**
   * Creates a new Page RecordBuilder.
   * @return A new Page RecordBuilder
   */
  public static org.djames.kafka.streams.example.model.Page.Builder newBuilder() {
    return new org.djames.kafka.streams.example.model.Page.Builder();
  }

  /**
   * Creates a new Page RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Page RecordBuilder
   */
  public static org.djames.kafka.streams.example.model.Page.Builder newBuilder(org.djames.kafka.streams.example.model.Page.Builder other) {
    if (other == null) {
      return new org.djames.kafka.streams.example.model.Page.Builder();
    } else {
      return new org.djames.kafka.streams.example.model.Page.Builder(other);
    }
  }

  /**
   * Creates a new Page RecordBuilder by copying an existing Page instance.
   * @param other The existing instance to copy.
   * @return A new Page RecordBuilder
   */
  public static org.djames.kafka.streams.example.model.Page.Builder newBuilder(org.djames.kafka.streams.example.model.Page other) {
    if (other == null) {
      return new org.djames.kafka.streams.example.model.Page.Builder();
    } else {
      return new org.djames.kafka.streams.example.model.Page.Builder(other);
    }
  }

  /**
   * RecordBuilder for Page instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Page>
    implements org.apache.avro.data.RecordBuilder<Page> {

    private int pageID;
    private java.lang.CharSequence category;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.djames.kafka.streams.example.model.Page.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pageID)) {
        this.pageID = data().deepCopy(fields()[0].schema(), other.pageID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.category)) {
        this.category = data().deepCopy(fields()[1].schema(), other.category);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Page instance
     * @param other The existing instance to copy.
     */
    private Builder(org.djames.kafka.streams.example.model.Page other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.pageID)) {
        this.pageID = data().deepCopy(fields()[0].schema(), other.pageID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.category)) {
        this.category = data().deepCopy(fields()[1].schema(), other.category);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'pageID' field.
      * @return The value.
      */
    public int getPageID() {
      return pageID;
    }


    /**
      * Sets the value of the 'pageID' field.
      * @param value The value of 'pageID'.
      * @return This builder.
      */
    public org.djames.kafka.streams.example.model.Page.Builder setPageID(int value) {
      validate(fields()[0], value);
      this.pageID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'pageID' field has been set.
      * @return True if the 'pageID' field has been set, false otherwise.
      */
    public boolean hasPageID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'pageID' field.
      * @return This builder.
      */
    public org.djames.kafka.streams.example.model.Page.Builder clearPageID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategory() {
      return category;
    }


    /**
      * Sets the value of the 'category' field.
      * @param value The value of 'category'.
      * @return This builder.
      */
    public org.djames.kafka.streams.example.model.Page.Builder setCategory(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.category = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'category' field.
      * @return This builder.
      */
    public org.djames.kafka.streams.example.model.Page.Builder clearCategory() {
      category = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Page build() {
      try {
        Page record = new Page();
        record.pageID = fieldSetFlags()[0] ? this.pageID : (java.lang.Integer) defaultValue(fields()[0]);
        record.category = fieldSetFlags()[1] ? this.category : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Page>
    WRITER$ = (org.apache.avro.io.DatumWriter<Page>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Page>
    READER$ = (org.apache.avro.io.DatumReader<Page>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.pageID);

    if (this.category == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.category);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.pageID = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.category = null;
      } else {
        this.category = in.readString(this.category instanceof Utf8 ? (Utf8)this.category : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.pageID = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.category = null;
          } else {
            this.category = in.readString(this.category instanceof Utf8 ? (Utf8)this.category : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










